# Generated by Django 5.1.1 on 2024-10-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_usercart_delete_usercard'),
        ('store', '0020_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to='store.product'),
        ),
    ]
