# Generated by Django 5.1.1 on 2024-10-26 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_usercart_products'),
        ('store', '0020_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'product')},
            },
        ),
    ]
