# Generated by Django 5.1.1 on 2024-10-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_usercart_name_usercart_quantities_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='usercart',
            name='quantities',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.usercart'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user_cart',
        ),
    ]
